### ISSUE TITLE
[US#128] [Task 02] Integração com o TS#01 para verificar dados de informação da bateria

### ISSUE THREAD

**Issue by oswaldocostaneto** [stepestr/ipbl2020#180]

**Comment by dcoutinhu** [comment]
Ficou definido que:
Sensor que ira monitorar o nível da bateria, retornando uma flag de "Bateria baixa" ao atingir determinado valor.

**Comment by dcoutinhu** [comment]
Devido ao Arduino utilizar 5V para seu funcionamento, será utilizado esse valor acrescido de lastro especificado por parametro.
